# Generated by Django 3.0.2 on 2020-07-04 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200704_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userscoretransaction',
            name='points',
            field=models.CharField(choices=[('profile', 1), ('referral', 1)], max_length=255),
        ),
    ]
